/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkRouteImport } from './routes/walk'
import { Route as TriviaRouteImport } from './routes/trivia'
import { Route as TokyoCairoRouteImport } from './routes/tokyo-cairo'
import { Route as LandmarksRouteImport } from './routes/landmarks'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FoodRouteImport } from './routes/food'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)
const TriviaRoute = TriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => rootRouteImport,
} as any)
const TokyoCairoRoute = TokyoCairoRouteImport.update({
  id: '/tokyo-cairo',
  path: '/tokyo-cairo',
  getParentRoute: () => rootRouteImport,
} as any)
const LandmarksRoute = LandmarksRouteImport.update({
  id: '/landmarks',
  path: '/landmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/culture': typeof CultureRoute
  '/experiences': typeof ExperiencesRoute
  '/food': typeof FoodRoute
  '/history': typeof HistoryRoute
  '/landmarks': typeof LandmarksRoute
  '/tokyo-cairo': typeof TokyoCairoRoute
  '/trivia': typeof TriviaRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/culture': typeof CultureRoute
  '/experiences': typeof ExperiencesRoute
  '/food': typeof FoodRoute
  '/history': typeof HistoryRoute
  '/landmarks': typeof LandmarksRoute
  '/tokyo-cairo': typeof TokyoCairoRoute
  '/trivia': typeof TriviaRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/culture': typeof CultureRoute
  '/experiences': typeof ExperiencesRoute
  '/food': typeof FoodRoute
  '/history': typeof HistoryRoute
  '/landmarks': typeof LandmarksRoute
  '/tokyo-cairo': typeof TokyoCairoRoute
  '/trivia': typeof TriviaRoute
  '/walk': typeof WalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/credits'
    | '/culture'
    | '/experiences'
    | '/food'
    | '/history'
    | '/landmarks'
    | '/tokyo-cairo'
    | '/trivia'
    | '/walk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/credits'
    | '/culture'
    | '/experiences'
    | '/food'
    | '/history'
    | '/landmarks'
    | '/tokyo-cairo'
    | '/trivia'
    | '/walk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/credits'
    | '/culture'
    | '/experiences'
    | '/food'
    | '/history'
    | '/landmarks'
    | '/tokyo-cairo'
    | '/trivia'
    | '/walk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreditsRoute: typeof CreditsRoute
  CultureRoute: typeof CultureRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FoodRoute: typeof FoodRoute
  HistoryRoute: typeof HistoryRoute
  LandmarksRoute: typeof LandmarksRoute
  TokyoCairoRoute: typeof TokyoCairoRoute
  TriviaRoute: typeof TriviaRoute
  WalkRoute: typeof WalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trivia': {
      id: '/trivia'
      path: '/trivia'
      fullPath: '/trivia'
      preLoaderRoute: typeof TriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokyo-cairo': {
      id: '/tokyo-cairo'
      path: '/tokyo-cairo'
      fullPath: '/tokyo-cairo'
      preLoaderRoute: typeof TokyoCairoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landmarks': {
      id: '/landmarks'
      path: '/landmarks'
      fullPath: '/landmarks'
      preLoaderRoute: typeof LandmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreditsRoute: CreditsRoute,
  CultureRoute: CultureRoute,
  ExperiencesRoute: ExperiencesRoute,
  FoodRoute: FoodRoute,
  HistoryRoute: HistoryRoute,
  LandmarksRoute: LandmarksRoute,
  TokyoCairoRoute: TokyoCairoRoute,
  TriviaRoute: TriviaRoute,
  WalkRoute: WalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
